Repository JuliaDynamics/Agents.jl, pull requests merged in 2020-03, with the labels that each got.

#168 Remove coord/vertex from API
  docs/src/api.md
  src/CA2D.jl
  src/core/agent_space_interaction.jl
  src/core/space.jl
  src/simulations/sample.jl
  test/api_tests.jl
  test/benchmark/mesa/forest_fire.jl
  test/interaction_tests.jl
  test/runtests.jl
  test/space_test.jl
Labels: breaking

#182 Two convenience syntaxes for getting model propertries and agents
  CHANGELOG.md
  examples/HK.jl
  examples/forest_fire.jl
  examples/schelling.jl
  examples/sir.jl
  examples/social_distancing.jl
  examples/wealth_distribution.jl
  src/core/agent_space_interaction.jl
  src/core/continuous_space.jl
  src/core/model.jl
  src/core/space.jl
  test/api_tests.jl
  test/benchmark/DynamicGrids/agents.jl
  test/benchmark/benchmark.jl
  test/benchmark/mesa/forest_fire.jl
  test/collisions_tests.jl
  test/interaction_tests.jl
  test/model_access.jl
  test/runtests.jl
Labels: breaking, simplification

#189 Additional documentation
  docs/src/api.md
  docs/src/tutorial.md
  src/core/model.jl
  src/core/space.jl
  src/simulations/step.jl
  test/api_tests.jl
Labels: discussion, documentation
