Repository JuliaDynamics/Agents.jl, pull requests merged in 2021-07, with the labels that each got.

#534 Activate GLMakie in the Documentation Pipeline
  .github/workflows/ci.yml
  docs/Project.toml
  docs/make.jl
  examples/battle.jl
  examples/daisyworld.jl
  examples/diffeq.jl
  examples/flock.jl
  examples/forest_fire.jl
  examples/fractal_growth.jl
  examples/game_of_life_2D_CA.jl
  examples/growing_bacteria.jl
  examples/hk.jl
  examples/maze.jl
  examples/measurements.jl
  examples/opinion_spread.jl
  examples/predator_prey_fast.jl
  examples/predator_prey_multiagent.jl
  examples/runners.jl
  examples/schelling.jl
  examples/schoolyard.jl
  examples/sir.jl
  examples/social_distancing.jl
  examples/sugarscape.jl
  examples/wealth_distribution.jl
Labels: documentation

#531 Continuous Space Pathfinding
  CHANGELOG.md
  docs/src/api.md
  docs/src/comparison.md
  docs/src/index.md
  src/Agents.jl
  src/deprecations.jl
  src/spaces/continuous.jl
  src/spaces/utilities.jl
  src/submodules/io/jld2_integration.jl
  src/submodules/pathfinding/all_pathfinders.jl
  src/submodules/pathfinding/astar.jl
  src/submodules/pathfinding/astar_continuous.jl
  src/submodules/pathfinding/astar_grid.jl
  test/astar_tests.jl
  test/continuousSpace_tests.jl
  test/jld2_tests.jl
Labels: GSOC, continuous

#520 Pathfinding rework
  CHANGELOG.md
  Project.toml
  docs/make.jl
  docs/src/api.md
  docs/src/index.md
  examples/maze.jl
  examples/rabbit_fox_hawk.jl
  examples/runners.jl
  src/Agents.jl
  src/spaces/continuous.jl
  src/spaces/grid.jl
  src/spaces/utilities.jl
  src/submodules/io/jld2_integration.jl
  src/submodules/pathfinding/all_pathfinders.jl
  src/submodules/pathfinding/astar.jl
  src/submodules/pathfinding/astar_continuous.jl
  src/submodules/pathfinding/astar_grid.jl
  src/submodules/pathfinding/grid_pathfinder.jl
  src/submodules/pathfinding/metrics.jl
  src/submodules/pathfinding/pathfinding_utils.jl
  test/astar_tests.jl
  test/grid_pathfinder_tests.jl
  test/jld2_tests.jl
  test/runtests.jl
Labels: GSOC, enhancement
